/run/initialize
/random/setSeeds 3 24 
/control/verbose 1
/tracking/verbose 0
/event/verbose 0
/gps/verbose 0
/gps/particle neutron
#/gps/pos/type Point
/gps/pos/type Beam
/gps/pos/centre 0 0 2 cm
#/gps/pos/shape Square
#/gps/pos/halfx 5 cm
#/gps/pos/halfy 5 cm
#/gps/pos/halfz 5 cm 
/gps/pos/shape Circle
/gps/pos/radius 2.52 cm
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
#/gps/ang/type iso
/gps/ene/type Lin
/gps/ene/min .5 MeV
/gps/ene/max 50 MeV
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/direction 0 0 -1
#/run/beamOn 10000000
/run/beamOn 10000000